import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { getAddress } from '../../services/apiGeocoding';

// Define the initial state for the user slice
const initialState = {
  username: '',
  status: 'idle',
  position: {},
  address: '',
  error: '',
};

// Create the user slice
const userSlice = createSlice({
  name: 'user',
  initialState,

  reducers: {
    updateName(state, action) {
      state.username = action.payload;
    },
  },

  // Handle the different states of the asynchronous fetchAddress thunk
  extraReducers: (builder) =>
    builder
      .addCase(fetchAddress.pending, (state) => {
        state.status = 'loading';
      })

      .addCase(fetchAddress.fulfilled, (state, action) => {
        state.position = action.payload.position;
        state.address = action.payload.address;
        state.status = 'idle';
      })

      .addCase(fetchAddress.rejected, (state) => {
        state.status = 'error';
        state.error =
          'There was a problem getting your address. Make sure to fill this field!';
      }),
});

// Create an asynchronous thunk for getting the user's current address
export const fetchAddress = createAsyncThunk(
  'user/fetchAddress',
  async function () {
    // 1. Get the user's current geographical position from the browser
    const positionObj = await getPosition();

    const position = {
      latitude: positionObj.coords.latitude,
      longitude: positionObj.coords.longitude,
    };

    // 2. Use the coordinates to get the user's address from a reverse geocoding API
    const addressObj = await getAddress(position);

    const address = `${addressObj?.locality}, ${addressObj?.city} ${addressObj?.postcode}, ${addressObj?.countryName}`;

    // 3. Return only the data we need to store in Redux
    // This becomes action.payload when the thunk is fulfilled
    return { position, address };
  }
);

// Export the action creator automatically generated by createSlice
export const { updateName } = userSlice.actions;

// Export the reducer function to be added to the Redux store
export default userSlice.reducer;

// Wrap the browser's geolocation API in a Promise
// so we can use async/await with it
function getPosition() {
  return new Promise(function (resolve, reject) {
    navigator.geolocation.getCurrentPosition(resolve, reject);
  });
}