import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the user slice
const initialState = {
  username: '',
};

// Create the user slice
const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    updateName(state, action) {
      state.username = action.payload;
    },
  },
});

// Export the action creator automatically generated by createSlice
export const { updateName } = userSlice.actions;

// Export the reducer function to be added to the Redux store
export default userSlice.reducer;